// Re-export carrier types from shared types package
export type {
  Carrier,
  CSAScores,
  PreferredLane,
  CarrierContact,
  CarrierDocument,
  CreateCarrierRequest as CreateCarrierDto,
  UpdateCarrierRequest as UpdateCarrierDto,
  CreateCarrierContactRequest as CarrierContactDto,
  UpdateCarrierContactRequest as UpdateCarrierContactDto,
  CarrierRatingRequest as CarrierRatingDto,
  CarrierFilters as CarrierFiltersDto,
  CreateCarrierResponse,
  UpdateCarrierResponse,
  GetCarrierResponse,
  GetCarriersResponse,
  DeleteCarrierResponse,
  CreateCarrierContactResponse,
  UpdateCarrierContactResponse,
  DeleteCarrierContactResponse,
  CarrierStatistics as CarrierStatisticsDto,
  CarrierPerformance as CarrierPerformanceDto,
  CarrierOnboarding as CarrierOnboardingDto,
  InsuranceAlert as InsuranceAlertDto,
  GetInsuranceAlertsResponse,
  FMCSAVerification as FMCSAVerificationDto,
  VerifyFMCSARequest,
  VerifyFMCSAResponse,
  CarrierLoadData,
  GetCarrierLoadsResponse,
  CarrierExportData,
  Address,
} from "@tms/shared-types";
