// Re-export customer types from shared types package
export type {
  Customer,
  CustomerContact,
  CustomerContactData,
  CreateCustomerRequest as CreateCustomerDto,
  UpdateCustomerRequest as UpdateCustomerDto,
  CreateCustomerContactRequest as CustomerContactDto,
  UpdateCustomerContactRequest as UpdateCustomerContactDto,
  CustomerFilters as CustomerFiltersDto,
  CreateCustomerResponse,
  UpdateCustomerResponse,
  GetCustomerResponse,
  GetCustomersResponse,
  DeleteCustomerResponse,
  CreateCustomerContactResponse,
  UpdateCustomerContactResponse,
  DeleteCustomerContactResponse,
  CustomerStatistics,
  CustomerPerformance,
  CustomerLoadData,
  CustomerExportData,
  Address,
} from "@tms/shared-types";
