// Re-export load types from shared types package
export type {
  Load,
  LoadStatus,
  EquipmentType,
  LoadType,
  Dimensions,
  Accessorial,
  LoadCustomer,
  LoadCarrier,
  LoadCreator,
  LoadEvent,
  LoadDocument,
  LoadTrackingInfo,
  CreateLoadRequest as CreateLoadDto,
  UpdateLoadRequest as UpdateLoadDto,
  LoadFilters as LoadFiltersDto,
  CreateLoadResponse,
  UpdateLoadResponse,
  GetLoadResponse,
  GetLoadsResponse,
  DeleteLoadResponse,
  LoadStatistics,
  LoadStatisticsByStatus,
  DashboardStats,
  LoadCreatedEventData,
  LoadUpdatedEventData,
  StatusChangeEventData,
  LoadEventData,
  CreateLoadEventRequest as LoadEventDto,
  LoadExportData,
  Address,
} from "@tms/shared-types";
